name: Auto Vercel Trigger

on:
  schedule:
    - cron: "0 */5 * * *"  # every 5 hours
  workflow_dispatch:       # manual run option

jobs:
  vercel-trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 6 hours limit for a single job (can increase if needed)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create trigger file
        run: |
          echo "Triggered at $(date)" > trigger_$(date +%s).txt

      - name: Commit and push trigger
        run: |
          git add .
          git commit -m "Auto trigger at $(date)" || echo "No changes to commit"
          git push || echo "Push failed"

      - name: Wait 4.8 hours (17280 seconds)
        run: sleep 17280

      - name: Delete trigger file
        run: |
          git rm trigger_*.txt || echo "No trigger file to remove"
          git commit -m "Cleanup after trigger at $(date)" || echo "No cleanup commit"
          git push || echo "Push failed"
